### PR TITLE
spankbang.com

### PR DESCRIPTION
**Pull request by robin-india**
Example page:
```
! https://spankbang.com/20nxo/video/teacher+armpits+forcibly+licked (NSFW)
spankbang.com##.ptgncdn_holder
```

### CODE REVIEW

**Comment by jspenguin2017** [comment]
NSFW! `https://spankbang.com/20nxo/video/teacher+armpits+forcibly+licked`

**Comment by robin-india** [comment]
The Travis CI build failed? What does that mean? Can someone help?

**Comment by jspenguin2017** [comment]
CI fails if it doesn't pass lint. The linter still needs some improvements, don't worry about it for now.

**Comment by robin-india** [comment]
Okay. Thanks for the explanation.

**Pull request merged**
