### PR TITLE
9 domains

### PR DESCRIPTION
**Pull request by DandelionSprout**
Note: I wrote `bastropenterprise.com,donaldsonvillechief.com,tricountyindependent.com,echo-pilot.com##.ad` as one entry with no separate example pages, since they all shared the same GUI and publishing house that I'm aware of.

Example pages:

```
! https://www.amny.com/
amny.com##.gridlove-posts.row > div:has(.gridlove-inject)
! https://www.agcanada.com/
agcanada.com##.leaderboard
! https://americanmilitarynews.com/
americanmilitarynews.com###blogposts > div:not(:has(a))
! (All four sites' respective frontpages)
bastropenterprise.com,donaldsonvillechief.com,tricountyindependent.com,echo-pilot.com##.ad
! https://www.dailypress.com/
dailypress.com##.pb-f-ads-dfp
dailypress.com##.pb-f-ads-nativo
dailypress.com##.pb-container:last-of-type
! https://www.ddtonline.com/
ddtonline.com##.block-inner:not(:has(a)):not(:has(iframe)):not(:has(form))
```

### CODE REVIEW

**Comment by liamengland1** [comment]
`dailypress.com##[class^="pb-f-ads"]`?

**Comment by jspenguin2017** [comment]
@llacb47 Considering there's only 2, the current rules are fine.

**Comment by jspenguin2017** [comment]
`https://www.amny.com/`

**Comment by jspenguin2017** [comment]
`https://www.agcanada.com/`

**Comment by jspenguin2017** [comment]
`https://americanmilitarynews.com/`

**Comment by jspenguin2017** [comment]
`https://www.bastropenterprise.com/`
`https://www.donaldsonvillechief.com/`
`https://www.tricountyindependent.com/`
`https://www.echo-pilot.com/`

**Comment by jspenguin2017** [comment]
`https://www.dailypress.com/`

**Comment by jspenguin2017** [comment]
`https://www.ddtonline.com/`

**Pull request merged**
