### PR TITLE
filehorse.com, simkl.com, color-hex.com, guidatv.quotidiano.net

### PR DESCRIPTION
**Pull request by DandelionSprout**
Same procedure as usual.

Example pages:

```
! https://guidatv.quotidiano.net/k2/
guidatv.quotidiano.net###Leader
! https://simkl.com/tv/49368/zack-and-quack/season-2/episode-19/
simkl.com##.blockplacecenter
! https://www.color-hex.com/
color-hex.com##hr
! https://www.filehorse.com/download-google-chrome-64/
filehorse.com##div[class^="dx-pr-"]
```

PS: You may or may not have been wondering why I haven't submitted any Nordic entries to this list, despite me being from that area? That is because my Nordic list aims to take care of empty boxes, as one of very few ad-removing lists to do so. So if you ever do get any requests about empty boxes on Norwegian or Danish websites, you are welcome to give me a FYI about it, if you want to.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
`https://guidatv.quotidiano.net/k2/`

**Comment by jspenguin2017** [comment]
`https://simkl.com/tv/49368/zack-and-quack/season-2/episode-19/`

**Comment by jspenguin2017** [comment]
`https://www.color-hex.com/`

**Comment by jspenguin2017** [comment]
`https://www.filehorse.com/download-google-chrome-64/`

**Comment by jspenguin2017** [comment]
Thanks for your contribution! 

I just noticed that you sometimes include extra comments in your PRs and I completely missed them. 

> https://github.com/NanoAdblockerLab/NanoContrib/pull/7
> By now I've exhausted most of my sources for sites that have empty placeholders.

If you're interested, there are a few more in the [QuickReports repository](https://github.com/NanoMeow/QuickReports/issues), they are all tagged as `t: ads`. 

<sup>Hint: Feel free to contribute to any issues tagged with `s: backlog`.</sup>

> https://github.com/NanoAdblockerLab/NanoContrib/pull/9
> I thought that more people would've been enthusiastic about this list

I would say most people are not bothered enough by some empty spaces to submit pull requests, and I don't have enough time to manage all the issues coming into my repositories. 

If you are interested in helping out, feel free to PR an issues template and I can enable issues in this repository.

**Comment by DandelionSprout** [comment]
>Hint: Feel free to contribute to any issues tagged with `s: backlog`.

I decided to do so just for the fun of it, and in those cases where I were able to replicate the problems (which was far from always), I've also left some comments and notes in them for you guys (You and seemingly also okiehsch) to check out. 🙂

**Comment by jspenguin2017** [comment]
Thanks! That was very helpful. 

About 60% of the issues in QuickReports repo are reproducible, so if you can't reproduce, just skip it. :)

**Pull request merged**
