### PR TITLE
nytimes.com, askapache.com

### PR DESCRIPTION
**Pull request by DandelionSprout**
A pretty simple pull this time around.

```
! https://www.nytimes.com/2019/12/23/us/matt-shea-washington-extremism.html
nytimes.com,nytimes3xbfgragh.onion##section[name=articleBody] > div:not(.StoryBodyCompanionColumn):not([data-testid]):not(:last-of-type)
! https://www.askapache.com/online-tools/htpasswd-generator/
askapache.com##.GAD
```

### CODE REVIEW

**Comment by jspenguin2017** [comment]
`https://www.nytimes.com/2019/12/23/us/matt-shea-washington-extremism.html`

**Comment by jspenguin2017** [comment]
`https://www.askapache.com/online-tools/htpasswd-generator/`

**Comment by yourduskquibbles** [comment]
@DandelionSprout 

`nytimes.com,nytimes3xbfgragh.onion##section[name=articleBody] > div:not(.StoryBodyCompanionColumn):not([data-testid]):not(:last-of-type)` is breaking site functions on some articles. 
Test Article Example: `https://www.nytimes.com/2020/01/28/world/asia/china-coronavirus.html`

`Read Updates in Chinese: 武汉疫情每日汇总中文版` & `Coronavirus Map` section blocked. 

The `Here's what you need to know` from original report[1] seems to not be on that particular page anymore but it was previously blocked.

animated gif with erroneous blocking shown is below:

nytimes4



I think you are just trying to remove the 1rem whitespace divs on `nytimes.com` articles with `nytimes.com,nytimes3xbfgragh.onion##section[name=articleBody] > div:not(.StoryBodyCompanionColumn):not([data-testid]):not(:last-of-type)`? 
nytimes

Maybe just replace with `nytimes.com##.css-190ncxp` so is more targeted to just the 1rem white space class?

nytimes2

[1]Original report: https://github.com/NanoMeow/QuickReports/issues/147#issuecomment-579337077

**Comment by jspenguin2017** [comment]
@yourduskquibbles Please feel free to create a Pull Request.

**Pull request merged**
