### PR TITLE
makeuseof.com

### PR DESCRIPTION
**Pull request by Collectathon**
MakeUseOf placeholder blocking.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
Do you have a test link?

**Comment by Collectathon** [comment]
`https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/`

I have tested the filter on this page.

**Comment by jspenguin2017** [comment]
Already fixed in EasyList? 
image

**Comment by Collectathon** [comment]
That does seem to be identical. However, I have the EasyList filter enabled and it seems to be letting it through.
web_webpage
Maybe it's just an issue on my end. The logger is showing that it isn't being blocked:

<details><summary>Logger output</summary>

```
+2
||facebook.com/tr/?
--
www.makeuseof.com
3
image
https://www.facebook.com/tr/?id=172826243054377&ev=fb_page_view&dl=https%3A%2F%2Fwww.makeuseof.com%2Ftag%2F5-best-dynamic-dns-providers-can-lookup-free-today%2F&rl=&if=false&ts=1599664077844&sw=1920&sh=1080&at=
```
```
+1
/oil.*-release.min.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/oil/oil.1.3.5-RELEASE.min.js
```
```
+1
/pixel.png?
--
www.makeuseof.com
1
xhr
https://www.makeuseof.com/pixel.png?params=---{%22group%22:%22browseclip_imp%22,%22device%22:%22desktop%22,%22ids%22:[{%22id%22:%22911106%22,%22position%22:%22sentinel-article-sidebarTop-1%22},{%22id%22:%22990021%22,%22position%22:%22sentinel-article-sidebarTop-2%22},{%22id%22:%22988333%22,%22position%22:%22sentinel-article-sidebarTop-3%22},{%22id%22:%22972475%22,%22position%22:%22sentinel-article-sidebarTop-4%22},{%22id%22:%22990134%22,%22position%22:%22sentinel-article-sidebarTop-5%22},{%22id%22:%22150084%22,%22position%22:%22sentinel-article-sidebarTop-6+%22},{%22id%22:%22981175%22,%22position%22:%22sentinel-article-sidebarSticky-1%22},{%22id%22:%22980098%22,%22position%22:%22sentinel-article-sidebarSticky-2%22},{%22id%22:%22991439%22,%22position%22:%22sentinel-article-sidebarSticky-3%22},{%22id%22:%22465532%22,%22position%22:%22sentinel-article-relatedContent-1%22},{%22id%22:%22722182%22,%22position%22:%22sentinel-article-relatedContent-2%22},{%22id%22:%22990765%22,%22position%22:%22sentinel-article-relatedContent-3%22},{%22id%22:%22586881%22,%22position%22:%22sentinel-article-relatedContent-4%22},{%22id%22:%22979104%22,%22position%22:%22sentinel-article-relatedContent-5%22},{%22id%22:%22978254%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22987285%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22981217%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22991402%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22715480%22,%22position%22:%22sentinel-article-nextArticle%22}],%22eventType%22:%22impression%22}---&rdm=0.320226227410092
```
```
+1
/iframedadtemplate/*
--
www.makeuseof.com
1
frame
https://www.makeuseof.com/iFramedAdTemplate/1804/tag/5-best-dynamic-dns-providers-can-lookup-free-today/&postId=463146/
```
```
+1
||mailerlite.com^$3p
--
www.makeuseof.com
3
script
https://static.mailerlite.com/js/w/webforms.min.js?v5c5d99c28cfe49b41fe82455507d7558
```
```
+1
||track.mailerlite.com^
--
www.makeuseof.com
3
image
https://track.mailerlite.com/webforms/o/2384299/r3i1n7?v1595538294
```
```
+1
amazon_apstag.js
<<
www.makeuseof.com
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+1
||amazon-adsystem.com^
--
www.makeuseof.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+1
||media.net^
--
www.makeuseof.com
3
script
https://hbx.media.net/bxl.js?cid=8CU6TM0R4&dn=www.makeuseof.com&https=1
```
```
+1
||doubleclick.net^
--
www.makeuseof.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+1
||a.quora.com^
--
www.makeuseof.com
3
script
https://a.quora.com/qevents.js
```
```
+1
googletagmanager.com/gtm.js
<<
www.makeuseof.com
script
https://www.googletagmanager.com/gtm.js?id=GTM-TBXVR8R
```
```
+1
||googletagmanager.com/gtm.js$script
--
www.makeuseof.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-TBXVR8R
```
```
+1
google-analytics.com/analytics.js
<<
www.makeuseof.com
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
www.makeuseof.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+1
/oil.*-release.min.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/oil/oil.1.3.5-RELEASE.min.js
```
```
+1
||mailerlite.com^$3p
--
www.makeuseof.com
3
script
https://static.mailerlite.com/js/w/webforms.min.js?v5c5d99c28cfe49b41fe82455507d7558
```
```
+1
||track.mailerlite.com^
--
www.makeuseof.com
3
image
https://track.mailerlite.com/webforms/o/2384299/r3i1n7?v1595538294
```
```
+1
||adlightning.com^
--
www.makeuseof.com
3
script
https://tagan.adlightning.com/valnet/op.js
```
```
+1
||indexww.com^
--
www.makeuseof.com
3
script
https://js-sec.indexww.com/ht/p/184735-252190346293640.js
```
```
+1
/build/dfp.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/dfp.js
```
```
+1
##+js(nostif, document.body.classList.add, 100)
www.makeuseof.com
dom
https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/
```
```
+0
https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/
```
</details>

<details><summary>Logger output with custom script</summary>

```
+1
||facebook.com/tr/?
--
www.makeuseof.com
3
image
https://www.facebook.com/tr/?id=172826243054377&ev=fb_page_view&dl=https%3A%2F%2Fwww.makeuseof.com%2Ftag%2F5-best-dynamic-dns-providers-can-lookup-free-today%2F&rl=&if=false&ts=1599664346169&sw=1920&sh=1080&at=
```
```
+1
##.ad-zone-container
www.makeuseof.com
dom
https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/
```
```
+1
/oil.*-release.min.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/oil/oil.1.3.5-RELEASE.min.js
```
```
+1
/pixel.png?
--
www.makeuseof.com
1
xhr
https://www.makeuseof.com/pixel.png?params=---{%22group%22:%22browseclip_imp%22,%22device%22:%22desktop%22,%22ids%22:[{%22id%22:%22972475%22,%22position%22:%22sentinel-article-sidebarTop-1%22},{%22id%22:%22424979%22,%22position%22:%22sentinel-article-sidebarTop-2%22},{%22id%22:%22978373%22,%22position%22:%22sentinel-article-sidebarTop-3%22},{%22id%22:%22981175%22,%22position%22:%22sentinel-article-sidebarTop-4%22},{%22id%22:%22986938%22,%22position%22:%22sentinel-article-sidebarTop-5%22},{%22id%22:%22990223%22,%22position%22:%22sentinel-article-sidebarTop-6+%22},{%22id%22:%22988878%22,%22position%22:%22sentinel-article-sidebarSticky-1%22},{%22id%22:%22976991%22,%22position%22:%22sentinel-article-sidebarSticky-2%22},{%22id%22:%22519685%22,%22position%22:%22sentinel-article-sidebarSticky-3%22},{%22id%22:%22991195%22,%22position%22:%22sentinel-article-relatedContent-1%22},{%22id%22:%22560982%22,%22position%22:%22sentinel-article-relatedContent-2%22},{%22id%22:%22988799%22,%22position%22:%22sentinel-article-relatedContent-3%22},{%22id%22:%22986839%22,%22position%22:%22sentinel-article-relatedContent-4%22},{%22id%22:%22586881%22,%22position%22:%22sentinel-article-relatedContent-5%22},{%22id%22:%22979104%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22722056%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22985842%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22989458%22,%22position%22:%22sentinel-article-relatedContent-6+%22},{%22id%22:%22715480%22,%22position%22:%22sentinel-article-nextArticle%22}],%22eventType%22:%22impression%22}---&rdm=0.5070772384368131
```
```
+1
/iframedadtemplate/*
--
www.makeuseof.com
1
frame
https://www.makeuseof.com/iFramedAdTemplate/1804/tag/5-best-dynamic-dns-providers-can-lookup-free-today/&postId=463146/
```
```
+1
||mailerlite.com^$3p
--
www.makeuseof.com
3
script
https://static.mailerlite.com/js/w/webforms.min.js?v5c5d99c28cfe49b41fe82455507d7558
```
```
+1
||track.mailerlite.com^
--
www.makeuseof.com
3
image
https://track.mailerlite.com/webforms/o/2384299/r3i1n7?v1595538294
```
```
+1
amazon_apstag.js
<<
www.makeuseof.com
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+1
||amazon-adsystem.com^
--
www.makeuseof.com
3
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+1
||media.net^
--
www.makeuseof.com
3
script
https://hbx.media.net/bxl.js?cid=8CU6TM0R4&dn=www.makeuseof.com&https=1
```
```
+1
||doubleclick.net^
--
www.makeuseof.com
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+1
||adlightning.com^
--
www.makeuseof.com
3
script
https://tagan.adlightning.com/valnet/op.js
```
```
+1
||indexww.com^
--
www.makeuseof.com
3
script
https://js-sec.indexww.com/ht/p/184735-252190346293640.js
```
```
+1
||a.quora.com^
--
www.makeuseof.com
3
script
https://a.quora.com/qevents.js
```
```
+1
/build/dfp.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/dfp.js
```
```
+1
googletagmanager.com/gtm.js
<<
www.makeuseof.com
script
https://www.googletagmanager.com/gtm.js?id=GTM-TBXVR8R
```
```
+1
||googletagmanager.com/gtm.js$script
--
www.makeuseof.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-TBXVR8R
```
```
+1
google-analytics.com/analytics.js
<<
www.makeuseof.com
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
www.makeuseof.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+1
/oil.*-release.min.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/oil/oil.1.3.5-RELEASE.min.js
```
```
+1
||mailerlite.com^$3p
--
www.makeuseof.com
3
script
https://static.mailerlite.com/js/w/webforms.min.js?v5c5d99c28cfe49b41fe82455507d7558
```
```
+1
||track.mailerlite.com^
--
www.makeuseof.com
3
image
https://track.mailerlite.com/webforms/o/2384299/r3i1n7?v1595538294
```
```
+1
||adlightning.com^
--
www.makeuseof.com
3
script
https://tagan.adlightning.com/valnet/op.js
```
```
+1
||indexww.com^
--
www.makeuseof.com
3
script
https://js-sec.indexww.com/ht/p/184735-252190346293640.js
```
```
+1
/build/dfp.js
--
www.makeuseof.com
1
script
https://www.makeuseof.com/public/build/dfp.js
```
```
+1
##+js(nostif, document.body.classList.add, 100)
www.makeuseof.com
dom
https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/
```
```
+0
https://www.makeuseof.com/tag/5-best-dynamic-dns-providers-can-lookup-free-today/
```
</details>

**Comment by jspenguin2017** [comment]
Are you sure you have the latest filters? I don't see that placeholder.

**Pull request closed without merging**
