### PR TITLE
11 Domains

### PR DESCRIPTION
**Pull request by DandelionSprout**
Hello. I've dug out a loose assortment of entries from my private filters to fill this new list with.

I'm unsure what more I'd need to say about this, but I'm open for questions on request.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
Hi, thanks for the pull request. 

Can you provide a test link for each domain for documentation? Also, are generic rules really needed? 

I certainly trust you that your rules are good, but as project owner, I need to make sure the project stays maintainable for the future.

**Comment by DandelionSprout** [comment]
Getting good example links could easily take me another half-hour, but sure thing, I guess.

**Comment by jspenguin2017** [comment]
There's no rush, take your time. Whenever you have time, doesn't have to be today.

**Comment by DandelionSprout** [comment]
I love to sort things in general, and adblock lists are one of them. Additionally, I was hoping to be able to do this before bedtime, so here's the example links.

* `avsforum.com##.large-4.medium-6.small-12:has([class=ad-wrapper])`: `https://www.avsforum.com/`
* `gadgethacks.com##.whtaph-floatbox`: `https://www.gadgethacks.com/`
* `tomshardware.*##.p-u-md-1-3.p-u-1:has(div[class*="block-ads"])`: `https://www.tomshardware.com/t/it-pro/` (.com example), `https://www.tomshardware.co.uk/t/it-pro/` (.co.uk example)
* Important note: The two Pixiv entries are for page versions that are *only* shown to logged-in users. Non-logged-in users will see completely different pages that have the same URLs. With that being said:
* `pixiv.net##.ads-top-info`: `https://www.pixiv.net/`
* `pixiv.net##._2vNejsc`: `https://www.pixiv.net/member_illust.php?mode=medium&illust_id=52634672`
* `mariowiki.com###mw-content-text > table > tbody > tr > td:nth-of-type(1)`: `https://www.mariowiki.com/WarioWare_Gold`
* `ssbwiki.com###mw-content-text > table > tbody > tr > td:nth-of-type(2)`: `https://www.ssbwiki.com/Main_Page`
* `issuu.com##div[class*="adPlacementContainer"]`: `https://issuu.com/upstatehouse/docs/upstate-house-spring-2018/26`
* `fileinfo.com##.linkAds`: `https://fileinfo.com/extension/json`
* `investopedia.com##.right-rail--ad-container`: `https://www.investopedia.com/`
* `investopedia.com###partnerlinks_1-0`: `https://www.investopedia.com/taxes/file-early-tax-return/`
* `lame.buanzo.org###ads`: `https://lame.buanzo.org/`
* `tvtropes.org##.sb-ad-unit`: `https://tvtropes.org/`
* `picktorrent.com##.aBut > .no2ref`: `https://www.picktorrent.com/download/disney-fairies-pixie-hollow-tales-05-rani-in-the-mermaid-lagoon-epub-mobi-k-t.html`
* `yeggi.com##.adbttm_right_300`: `https://www.yeggi.com/`

**Comment by DandelionSprout** [comment]
I've also chosen to remove the generic entries after all, in part because I couldn't remember which sites they applied to.

**Comment by jspenguin2017** [comment]
`https://www.avsforum.com/`

**Comment by jspenguin2017** [comment]
`https://www.gadgethacks.com/`

**Comment by jspenguin2017** [comment]
`https://www.tomshardware.com/t/it-pro/`
`https://www.tomshardware.co.uk/t/it-pro/`

**Comment by jspenguin2017** [comment]
Requires account, could be NSFW when logged in
`https://www.pixiv.net/`
`https://www.pixiv.net/member_illust.php?mode=medium&illust_id=52634672`

**Comment by jspenguin2017** [comment]
`https://www.mariowiki.com/WarioWare_Gold`

**Comment by jspenguin2017** [comment]
`https://www.ssbwiki.com/Main_Page`

**Comment by jspenguin2017** [comment]
`https://issuu.com/upstatehouse/docs/upstate-house-spring-2018/26`

**Comment by jspenguin2017** [comment]
`https://fileinfo.com/extension/json`

**Comment by jspenguin2017** [comment]
`https://www.investopedia.com/`
`https://www.investopedia.com/taxes/file-early-tax-return/`

**Comment by jspenguin2017** [comment]
`https://www.investopedia.com/taxes/file-early-tax-return/`

**Comment by jspenguin2017** [comment]
`https://lame.buanzo.org/`

**Comment by jspenguin2017** [comment]
`https://tvtropes.org/`

**Comment by jspenguin2017** [comment]
`https://www.picktorrent.com/download/disney-fairies-pixie-hollow-tales-05-rani-in-the-mermaid-lagoon-epub-mobi-k-t.html`

**Comment by jspenguin2017** [comment]
`https://www.yeggi.com/`

**Comment by jspenguin2017** [comment]
Looks good. Thanks.

**Comment by jspenguin2017** [comment]
These are moved to https://github.com/NanoAdblockerLab/NanoContrib/pull/5
```
https://www.mariowiki.com/WarioWare_Gold
https://www.ssbwiki.com/Main_Page
```

**Pull request merged**
