### PR TITLE
12 Domains

### PR DESCRIPTION
**Pull request by DandelionSprout**
Same routine as usual, it seems.

Example pages:

```
! https://mywindowshub.com/windows-and-education-how-microsoft-windows-make-students-life-easier/
mywindowshub.com##.textwidget:has(script[src*="adsbygoogle.js"])
! https://mywindowshub.com/
mywindowshub.com##.td-pb-span12.tdc-column.vc_column_container:has(ins[class="adsbygoogle"])
! https://www.download3k.com/articles/How-to-Resume-a-Failed-Windows-10-Installation-Media-Creation-01351
download3k.com##p:has(script[src*="adsbygoogle.js"])
! https://pureinfotech.com/avoid-problems-installing-windows-10-april-2018-update-1803/
pureinfotech.com##.code-block:has(script[src*="adsbygoogle.js"])
! https://windows101tricks.com/windows-10-fall-creators-update-installation-stuck/
windows101tricks.com##.single-post-content.clearfix.entry-content > div:has(script[src*="adsbygoogle.js"])
! https://www.itpro.co.uk/
itpro.co.uk##.block-dfp
! https://www.itpro.co.uk/operating-systems/27811/how-to-install-the-windows-10-creators-update-from-usb
itpro.co.uk###dfp-ad-lead_gen_native_slot
itpro.co.uk##.lazyadslot
! https://www.reddit.com/r/assholedesign/comments/acrjrf/why_the_foods_you_actually_get_dont_look_like_the/ (when clicking on it from a timeline)
reddit.com###overlay-comment-atf
! https://www.thedrum.com/news/2019/01/07/virtue-names-new-cco-vice-continues-focus-resources-its-ad-agency
thedrum.com##.nocontent.footer__more
thedrum.com##.outbrain
thedrum.com##.advert--wallpaper
! https://www.experts-exchange.com/questions/29127776/Linux-Resize-NTFS-Partition.html
experts-exchange.com##.adBanner-comment
! https://audio.online-convert.com/convert-to-aac
online-convert.com##.flex_banner_bottom
online-convert.com##div[class^="banner_"]:has(ins[class="adsbygoogle"])
! http://adsl.excite.it/sky-tv.html
excite.it##.cLeft.alpha.g_3
```

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I also added a fix for Mario Wiki and SSB Wiki, as the previous entries occasionally blanked out entire articles.

**Comment by jspenguin2017** [comment]
`https://mywindowshub.com/`
`https://mywindowshub.com/windows-and-education-how-microsoft-windows-make-students-life-easier/`

**Comment by jspenguin2017** [comment]
`https://www.download3k.com/articles/How-to-Resume-a-Failed-Windows-10-Installation-Media-Creation-01351`

**Comment by jspenguin2017** [comment]
`https://pureinfotech.com/avoid-problems-installing-windows-10-april-2018-update-1803/`

**Comment by jspenguin2017** [comment]
`https://windows101tricks.com/windows-10-fall-creators-update-installation-stuck/`

**Comment by jspenguin2017** [comment]
`https://www.itpro.co.uk/`
`https://www.itpro.co.uk/operating-systems/27811/how-to-install-the-windows-10-creators-update-from-usb`

**Comment by jspenguin2017** [comment]
When clicking on it from a timeline
`https://www.reddit.com/r/assholedesign/comments/acrjrf/why_the_foods_you_actually_get_dont_look_like_the/`

**Comment by jspenguin2017** [comment]
`https://www.thedrum.com/news/2019/01/07/virtue-names-new-cco-vice-continues-focus-resources-its-ad-agency`

**Comment by jspenguin2017** [comment]
`https://www.experts-exchange.com/questions/29127776/Linux-Resize-NTFS-Partition.html`

**Comment by jspenguin2017** [comment]
`https://audio.online-convert.com/convert-to-aac`

**Comment by jspenguin2017** [comment]
`http://adsl.excite.it/sky-tv.html`

**Comment by jspenguin2017** [comment]
`https://www.mariowiki.com/WarioWare_Gold`
`https://www.ssbwiki.com/Main_Page`

**Pull request merged**
