### PR TITLE
universitystar.com, happymag.tv, reason.com, bigthink.com, realclearpolicy.com

### PR DESCRIPTION
**Pull request by DandelionSprout**
If I've calculated correctly, this pull request should give this list more entries than [AdGuard's own box removal list](https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/remains.txt)!... which I only learned about the existence of three weeks ago (as it was hid deep inside their annoyances list). 😅

Example pages:

```
! https://universitystar.com/33233/opinions/cancel-culture-is-toxic/
universitystar.com###leaderboard
! https://happymag.tv/cancel-culture-wins-macquarie-dictionarys-2019-word-of-the-year/
happymag.tv##.g
! https://reason.com/2019/11/11/donald-trump-jr-ucla-book-student-silence/
reason.com##.magicSidebar
! https://bigthink.com/surprising-science/golden-blood
bigthink.com##.rebellt-item:not(:has(a))
! https://www.realclearpolicy.com/2019/10/02/the_atavism_of_cancel_culture_42991.html
realclearpolicy.com##div[style*="float: left; width: 300px;"]
```

### CODE REVIEW

**Comment by jspenguin2017** [comment]
`https://universitystar.com/33233/opinions/cancel-culture-is-toxic/`

**Comment by jspenguin2017** [comment]
`https://happymag.tv/cancel-culture-wins-macquarie-dictionarys-2019-word-of-the-year/`

**Comment by jspenguin2017** [comment]
`https://reason.com/2019/11/11/donald-trump-jr-ucla-book-student-silence/`

**Comment by jspenguin2017** [comment]
`https://bigthink.com/surprising-science/golden-blood`

**Comment by jspenguin2017** [comment]
`https://www.realclearpolicy.com/2019/10/02/the_atavism_of_cancel_culture_42991.html`

**Comment by jspenguin2017** [comment]
Interesting, I didn't know they had that neither. 
Why did they put it in their annoyance list? Shouldn't those belong to the main filter along with other ads related rules?

**Comment by DandelionSprout** [comment]
Honestly I have no idea, except possibly for how AdGuard has overly narrow definitions for what counts as blockable ads.

**Pull request merged**
