### PR TITLE
nfl.com, tasteofhome.com, deviantart.com

### PR DESCRIPTION
**Pull request by DandelionSprout**
Example pages:
```
! http://www.nfl.com/videos/nfl-game-highlights/0ap3000001064689/Joey-Slye-s-super-rare-fair-catch-kick-attempt-is-wide-right
nfl.com##.video-channel-rr
! https://www.tasteofhome.com/recipes/chicken-quesadillas/
tasteofhome.com##.taboola-container
! https://www.deviantart.com/kittmouri/art/Ustream-Miele-174091566
||deviantart.com/_adslot/$subdocument
```

### CODE REVIEW

**Comment by DandelionSprout** [comment]
Note that I've placed `deviantART` in the NSFW category, despite the example page actually being SFW. The reasons for it should be obvious for those who've ever browsed casually around on DA at any point in their lives.

**Comment by jspenguin2017** [comment]
`http://www.nfl.com/videos/nfl-game-highlights/0ap3000001064689/Joey-Slye-s-super-rare-fair-catch-kick-attempt-is-wide-right`

**Comment by jspenguin2017** [comment]
`https://www.tasteofhome.com/recipes/chicken-quesadillas/`

**Comment by jspenguin2017** [comment]
NSFW! `https://www.deviantart.com/kittmouri/art/Ustream-Miele-174091566`

**Pull request merged**
