### PR TITLE
businessinsider.jp, game8.jp, lifehacker.jp, sankei.com, nicoco.net

### PR DESCRIPTION
**Pull request by DandelionSprout**
Example pages:

```
! https://www.businessinsider.jp/
businessinsider.jp##div:has(:scope > #bi_normal-2)
! https://game8.jp/
game8.jp##.l-jack__top_container
! https://www.lifehacker.jp/2020/01/block-internet-explorers-latest-vulnerability-with-this.html
lifehacker.jp##.lh-banner
! https://www.sankei.com/
sankei.com##div[style="width:300px;height:600px;"]:not(:has-text(/\S))
sankei.com##.row:has(div[id^="div-gpt-ad"])
! http://nicoco.net/
nicoco.net###search_form + div
```

### CODE REVIEW

**Review by jspenguin2017 — CHANGES_REQUESTED** [review]
Please move README changes to another PR.

**Comment by DandelionSprout** [comment]
Noted. But I'm very soon to head off for floorhockey practice, so I can only do it in about 3 hours' time, unfortunately.

**Comment by DandelionSprout** [comment]
I believe I've removed the notes from this PR now.

**Review by jspenguin2017 — APPROVED** [review]

**Comment by jspenguin2017** [comment]
`https://www.businessinsider.jp/`

**Comment by jspenguin2017** [comment]
`https://game8.jp/`

**Comment by jspenguin2017** [comment]
`https://www.lifehacker.jp/2020/01/block-internet-explorers-latest-vulnerability-with-this.html`

**Comment by jspenguin2017** [comment]
`https://www.sankei.com/`

**Comment by jspenguin2017** [comment]
`http://nicoco.net/`

**Pull request merged**
